#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=out/slurm_output_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

# conda env remove -n my_research_env || true
conda env create -f code/snellius_scripts/environment.yml

source activate my_research_env

python -c "import duckdb; print(f'DuckDB version: {duckdb.__version__}')"
# python -c "import darts; print(f'Darts version: {darts.__version__}')"