#!/bin/bash
#SBATCH --job-name=aggregate-hourly
#SBATCH --output=logs/output_%j.log
#SBATCH --error=logs/error_%j.err
#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --time=04:00:00
#SBATCH --mem=64G
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jialong.bao@student.uva.nl

module purge
module load 2025
module load Anaconda3/2025.06-1

# 2. Activate conda environment 
source activate my_research_env

# Run the notebook (headless)
jupyter nbconvert \
  --to notebook \
  --execute $HOME/NS_Thesis/all_code/3_model_training/classification/classification_base.ipynb \
  --ExecutePreprocessor.timeout=-1 \
  --output $HOME/NS_Thesis/executed_${SLURM_JOB_ID}.ipynb
