#!/bin/bash
#SBATCH --job-name=regression-base
#SBATCH --output=logs/output_%j.log
#SBATCH --error=logs/error_%j.err
#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --time=04:00:00
#SBATCH --mem=64G
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=yourmail@example.com

module purge
module load 2025
module load Anaconda3/2025.06-1

# # Create a temp directory on the compute node's local NVMe (fastest)
# mkdir -p "$TMPDIR/duckdb_temp"
# export DUCKDB_TMP="$TMPDIR/duckdb_temp"

# # 1. Copy your data to the compute node's local storage
# cp -r $HOME/NS_Thesis/data/filtered/full_dataset_partitioned $TMPDIR/

# 2. Activate conda environment 
source activate my_research_env

# # 3. Verify DuckDB is accessible (Optional debugging step)
# python -c "import duckdb; print(f'DuckDB version: {duckdb.__version__}')"
# # 3. Verify DuckDB is accessible (Optional debugging step)
# python -c "import darts; print(f'Darts version: {darts.__version__}')"

# 2. Run your code, 
# Note: The folder is now at $TMPDIR/full_dataset_partitioned
# srun python $HOME/NS_Thesis/code/classification/classification_baselines.py --data_dir $TMPDIR/full_dataset_partitioned

# Run the notebook (headless)
jupyter nbconvert \
  --to notebook \
  --execute $HOME/NS_Thesis/all_code/2_eda_and_time_series_data_creation/22_main_dataset_creation.ipynb \
  --ExecutePreprocessor.timeout=-1 \
  --output executed_${SLURM_JOB_ID}.ipynb


# # 3. Create a folder in your home to store them (if it doesn't exist)
# mkdir -p $HOME/NS_Thesis/models/
# mkdir -p $HOME/NS_Thesis/results/

# # 3. Copy the models back
# # This grabs all .pkl files from scratch and moves them to your home
# cp *.pkl $HOME/NS_Thesis/models/
# # Copy all CSVs from scratch to home
# cp *.csv $HOME/NS_Thesis/results/